using System.Text.Json.Serialization;

namespace Infrastructure.Data.DataSeeding.DataSeedingDTOs
{
    /// <summary>
    /// Data Transfer Object (DTO) for seeding the AircraftConfig entity.
    /// It maps the JSON file properties to the entity properties using JsonPropertyName.
    /// The ConfigId (IDENTITY) is intentionally excluded as it's generated by the database.
    /// </summary>
    public class AircraftConfigSeedDto
    {
        
        [JsonPropertyName("aircraft_fk")]
        public string AircraftId { get; set; }
 
        [JsonPropertyName("configuration_name")]
        public string ConfigurationName { get; set; }
         
        [JsonPropertyName("total_seats_count")]
        public int? TotalSeatsCount { get; set; }
         
        [JsonPropertyName("IsDeleted")]
        public bool IsDeleted { get; set; }
    }
}