using System.Text.Json.Serialization;

namespace Infrastructure.Data.DataSeeding.DataSeedingDTOs
{
    /// <summary>
    /// Data Transfer Object for AncillaryProduct entity seeding.
    /// Ensures professional mapping between JSON file attributes and the Entity model.
    /// Note: ProductId is omitted as it is an IDENTITY column and will be generated by the database.
    /// </summary>
    public class AncillaryProductSeedDto
    {
        // Name (Required) - Matches the 'name' column in the SQL schema
        [JsonPropertyName("name")]
        public string Name { get; set; }

        // Category (Optional) - Matches the 'category' column
        [JsonPropertyName("category")]
        public string? Category { get; set; }

        // BaseCost (Optional) - Matches the 'base_cost' column
        [JsonPropertyName("base_cost")]
        public decimal? BaseCost { get; set; }

        // UnitOfMeasure (Optional) - Matches the 'unit_of_measure' column
        [JsonPropertyName("unit_of_measure")]
        public string? UnitOfMeasure { get; set; }

        // IsDeleted (Required - Defaulted to false in the database, but included for complete mapping)
        [JsonPropertyName("is_deleted")]
        public bool IsDeleted { get; set; }
    }
}