using System.Text.Json.Serialization;

namespace Infrastructure.Data.DataSeeding.DataSeedingDTOs
{
    /// <summary>
    /// Data Transfer Object (DTO) for seeding the Seat entity.
    /// Used to deserialize data from Seat.json professionally.
    /// The SeatId is a unique string Primary Key, generated by combining AircraftId and SeatNumber.
    /// </summary>
    public class SeatSeedDto
    { 
        [JsonPropertyName("SeatId")]
        public string SeatId { get; set; } = string.Empty;
         
        [JsonPropertyName("AircraftId")]
        public string AircraftId { get; set; } = string.Empty;
         
        [JsonPropertyName("SeatNumber")]
        public string SeatNumber { get; set; } = string.Empty;
         
        [JsonPropertyName("CabinClassId")]
        public int CabinClassId { get; set; }
         
        [JsonPropertyName("IsWindow")]
        public bool? IsWindow { get; set; }
         
        [JsonPropertyName("IsExitRow")]
        public bool? IsExitRow { get; set; } 
        [JsonPropertyName("IsDeleted")]
        public bool IsDeleted { get; set; } = false;
    }
}