// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251130192331_AsiaporeairDbTesting")]
    partial class AsiaporeairDbTesting
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Department")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.HasKey("AppUserId");

                    b.HasIndex("AddedById");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Aircraft", b =>
                {
                    b.Property<string>("TailNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("tail_number");

                    b.Property<DateTime?>("AcquisitionDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("acquisition_date");

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_fk");

                    b.Property<string>("AirlineId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("airline_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("TotalFlightHours")
                        .HasColumnType("int")
                        .HasColumnName("total_flight_hours");

                    b.HasKey("TailNumber");

                    b.HasIndex("AircraftTypeId");

                    b.HasIndex("AirlineId");

                    b.ToTable("aircraft", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AircraftConfig", b =>
                {
                    b.Property<int>("ConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("config_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ConfigId"));

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("aircraft_fk");

                    b.Property<string>("ConfigurationName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("configuration_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("TotalSeatsCount")
                        .HasColumnType("int")
                        .HasColumnName("total_seats_count");

                    b.HasKey("ConfigId");

                    b.HasIndex("AircraftId");

                    b.ToTable("aircraft_config", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AircraftType", b =>
                {
                    b.Property<int>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("type_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TypeId"));

                    b.Property<decimal?>("CargoCapacity")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("cargo_capacity");

                    b.Property<int?>("CruisingVelocity")
                        .HasColumnType("int")
                        .HasColumnName("cruising_velocity");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("manufacturer");

                    b.Property<int?>("MaxSeats")
                        .HasColumnType("int")
                        .HasColumnName("max_seats");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("model");

                    b.Property<int?>("RangeKm")
                        .HasColumnType("int")
                        .HasColumnName("range_km");

                    b.HasKey("TypeId");

                    b.ToTable("aircraft_type", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Airline", b =>
                {
                    b.Property<string>("IataCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("iata_code");

                    b.Property<string>("BaseAirportId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("base_airport_fk");

                    b.Property<string>("Callsign")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("callsign");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.Property<string>("OperatingRegion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("operating_region");

                    b.HasKey("IataCode");

                    b.HasIndex("BaseAirportId");

                    b.ToTable("airline", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Airport", b =>
                {
                    b.Property<string>("IataCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("iata_code");

                    b.Property<int?>("Altitude")
                        .HasColumnType("int")
                        .HasColumnName("altitude");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("city");

                    b.Property<string>("CountryId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("country_fk");

                    b.Property<string>("IcaoCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)")
                        .HasColumnName("icao_code");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("latitude");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IataCode");

                    b.HasIndex("CountryId");

                    b.HasIndex("IcaoCode")
                        .IsUnique();

                    b.ToTable("airport", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AncillaryProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("product_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<decimal?>("BaseCost")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_cost");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("category");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("UnitOfMeasure")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("unit_of_measure");

                    b.HasKey("ProductId");

                    b.ToTable("ancillary_product", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AncillarySale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("sale_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal?>("PricePaid")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_paid");

                    b.Property<int>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_fk");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.Property<int?>("SegmentId")
                        .HasColumnType("int")
                        .HasColumnName("segment_fk");

                    b.HasKey("SaleId");

                    b.HasIndex("BookingId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SegmentId");

                    b.ToTable("ancillary_sale", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DATETIME2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("DATETIME2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfilePictureUrl")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Attendant", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AddedById");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("attendant", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BoardingPass", b =>
                {
                    b.Property<int>("PassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("pass_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassId"));

                    b.Property<DateTime?>("BoardingTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("boarding_time");

                    b.Property<int>("BookingPassengerBookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_passenger_booking_id");

                    b.Property<int>("BookingPassengerPassengerId")
                        .HasColumnType("int")
                        .HasColumnName("booking_passenger_passenger_id");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool?>("PrecheckStatus")
                        .HasColumnType("bit")
                        .HasColumnName("precheck_status");

                    b.Property<string>("SeatId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seat_fk");

                    b.HasKey("PassId");

                    b.HasIndex("SeatId");

                    b.HasIndex("BookingPassengerBookingId", "BookingPassengerPassengerId");

                    b.ToTable("boarding_pass", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Property<int>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("booking_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingId"));

                    b.Property<string>("BookingRef")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("booking_ref");

                    b.Property<DateTime>("BookingTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("booking_time");

                    b.Property<string>("FareBasisCodeId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fare_basis_code_fk");

                    b.Property<int>("FlightInstanceId")
                        .HasColumnType("int")
                        .HasColumnName("flight_instance_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("payment_status");

                    b.Property<bool>("PointsAwarded")
                        .HasColumnType("bit")
                        .HasColumnName("PointsAwarded");

                    b.Property<decimal?>("PriceTotal")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("price_total");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_fk");

                    b.HasKey("BookingId");

                    b.HasIndex("FareBasisCodeId");

                    b.HasIndex("FlightInstanceId");

                    b.HasIndex("UserId");

                    b.ToTable("booking", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.BookingPassenger", b =>
                {
                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_id")
                        .HasColumnOrder(0);

                    b.Property<int>("PassengerId")
                        .HasColumnType("int")
                        .HasColumnName("passenger_id")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("SeatAssignmentId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seat_assignment_fk");

                    b.HasKey("BookingId", "PassengerId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SeatAssignmentId")
                        .HasDatabaseName("IX_booking_passenger_seat_assignment_fk");

                    b.ToTable("booking_passenger", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CabinClass", b =>
                {
                    b.Property<int>("CabinClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cabin_class_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CabinClassId"));

                    b.Property<int>("ConfigId")
                        .HasColumnType("int")
                        .HasColumnName("config_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("name");

                    b.HasKey("CabinClassId");

                    b.HasIndex("ConfigId");

                    b.ToTable("cabin_class", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Certification", b =>
                {
                    b.Property<int>("CertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("cert_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CertId"));

                    b.Property<int>("CrewMemberId")
                        .HasColumnType("int")
                        .HasColumnName("crew_member_fk");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiry_date");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("issue_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("type");

                    b.HasKey("CertId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("certification", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.ContextualPricingAttributes", b =>
                {
                    b.Property<int>("AttributeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("attribute_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttributeId"));

                    b.Property<string>("CompetitorFares")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("competitor_fares");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int?>("LengthOfStay")
                        .HasColumnType("int")
                        .HasColumnName("length_of_stay");

                    b.Property<int?>("TimeUntilDeparture")
                        .HasColumnType("int")
                        .HasColumnName("time_until_departure");

                    b.Property<decimal?>("WillingnessToPay")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("willingness_to_pay");

                    b.HasKey("AttributeId");

                    b.ToTable("contextual_pricing_attributes", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Property<string>("IsoCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("iso_code");

                    b.Property<string>("Continent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("continent_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("name");

                    b.HasKey("IsoCode");

                    b.ToTable("country", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CrewMember", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("CrewBaseAirportId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("crew_base_airport_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("position");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CrewBaseAirportId");

                    b.ToTable("crew_member", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<DateTime?>("DateOfHire")
                        .HasColumnType("DATE")
                        .HasColumnName("date_of_hire");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("salary");

                    b.Property<int?>("ShiftPreferenceFk")
                        .HasColumnType("int")
                        .HasColumnName("shift_preference_fk");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("employee", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FareBasisCode", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("code");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Rules")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rules");

                    b.HasKey("Code");

                    b.ToTable("fare_basis_code", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FlightCrew", b =>
                {
                    b.Property<int>("FlightInstanceId")
                        .HasColumnType("int")
                        .HasColumnName("flight_instance_fk")
                        .HasColumnOrder(0);

                    b.Property<int>("CrewMemberId")
                        .HasColumnType("int")
                        .HasColumnName("crew_member_fk")
                        .HasColumnOrder(1);

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("role");

                    b.HasKey("FlightInstanceId", "CrewMemberId");

                    b.HasIndex("CrewMemberId");

                    b.ToTable("flight_crew", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FlightInstance", b =>
                {
                    b.Property<int>("InstanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("instance_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InstanceId"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_arr_ts");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("datetime2")
                        .HasColumnName("actual_dep_ts");

                    b.Property<string>("AircraftId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("aircraft_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_fk");

                    b.Property<DateTime>("ScheduledArrival")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_arr_ts");

                    b.Property<DateTime>("ScheduledDeparture")
                        .HasColumnType("datetime2")
                        .HasColumnName("scheduled_dep_ts");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("status");

                    b.HasKey("InstanceId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("flight_instance", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FlightLegDef", b =>
                {
                    b.Property<int>("LegDefId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("leg_def_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LegDefId"));

                    b.Property<string>("ArrivalAirportId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("arrival_airport_fk");

                    b.Property<string>("DepartureAirportId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("departure_airport_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("ScheduleId")
                        .HasColumnType("int")
                        .HasColumnName("schedule_fk");

                    b.Property<int>("SegmentNumber")
                        .HasColumnType("int")
                        .HasColumnName("segment_number");

                    b.HasKey("LegDefId");

                    b.HasIndex("ArrivalAirportId");

                    b.HasIndex("DepartureAirportId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("flight_leg_def", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FlightSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int")
                        .HasColumnName("aircraft_type_fk");

                    b.Property<string>("AirlineId")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("airline_fk");

                    b.Property<DateTime>("ArrivalTimeScheduled")
                        .HasColumnType("datetime2")
                        .HasColumnName("arrival_time_scheduled");

                    b.Property<byte?>("DaysOfWeek")
                        .HasColumnType("tinyint")
                        .HasColumnName("days_of_week");

                    b.Property<DateTime>("DepartureTimeScheduled")
                        .HasColumnType("datetime2")
                        .HasColumnName("departure_time_scheduled");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("flight_no");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_fk");

                    b.HasKey("ScheduleId");

                    b.HasIndex("AircraftTypeId");

                    b.HasIndex("AirlineId");

                    b.HasIndex("RouteId");

                    b.ToTable("flight_schedule", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.FrequentFlyer", b =>
                {
                    b.Property<int>("FlyerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("flyer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FlyerId"));

                    b.Property<int?>("AwardPoints")
                        .HasColumnType("int")
                        .HasColumnName("award_points");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("card_number");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("level");

                    b.HasKey("FlyerId");

                    b.ToTable("frequent_flyer", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Passenger", b =>
                {
                    b.Property<int>("PassengerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("passenger_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PassengerId"));

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("last_name");

                    b.Property<string>("PassportNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("passport_number");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_fk");

                    b.HasKey("PassengerId");

                    b.HasIndex("UserId");

                    b.ToTable("passenger", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("payment_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("amount");

                    b.Property<int>("BookingId")
                        .HasColumnType("int")
                        .HasColumnName("booking_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("method");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("transaction_datetime");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("PaymentId");

                    b.HasIndex("BookingId");

                    b.ToTable("payment", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Pilot", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("employee_id");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AircraftTypeId")
                        .HasColumnType("int")
                        .HasColumnName("type_rating_fk");

                    b.Property<int?>("AircraftTypeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastSimCheckDate")
                        .HasColumnType("DATE")
                        .HasColumnName("last_sim_check_date");

                    b.Property<string>("LicenseNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("license_number");

                    b.Property<int?>("TotalFlightHours")
                        .HasColumnType("int")
                        .HasColumnName("total_flight_hours");

                    b.HasKey("EmployeeId");

                    b.HasIndex("AddedById");

                    b.HasIndex("AircraftTypeId");

                    b.HasIndex("AircraftTypeTypeId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.ToTable("pilot", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.PriceOfferLog", b =>
                {
                    b.Property<int>("OfferId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("offer_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferId"));

                    b.Property<int?>("AncillaryId")
                        .HasColumnType("int")
                        .HasColumnName("ancillary_fk");

                    b.Property<int>("ContextAttributesId")
                        .HasColumnType("int")
                        .HasColumnName("context_attributes_fk");

                    b.Property<string>("FareId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("fare_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<decimal>("OfferPriceQuote")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("offer_price_quote");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int")
                        .HasColumnName("product_fk");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2")
                        .HasColumnName("timestamp");

                    b.HasKey("OfferId");

                    b.HasIndex("AncillaryId");

                    b.HasIndex("ContextAttributesId");

                    b.HasIndex("FareId");

                    b.ToTable("price_offer_log", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Property<int>("RouteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("route_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RouteId"));

                    b.Property<string>("DestinationAirportId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("destination_airport_fk");

                    b.Property<int?>("DistanceKm")
                        .HasColumnType("int")
                        .HasColumnName("distance_km");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<string>("OriginAirportId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)")
                        .HasColumnName("origin_airport_fk");

                    b.HasKey("RouteId");

                    b.HasIndex("DestinationAirportId");

                    b.HasIndex("OriginAirportId");

                    b.ToTable("route", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.RouteOperator", b =>
                {
                    b.Property<int>("RouteId")
                        .HasColumnType("int")
                        .HasColumnName("route_fk")
                        .HasColumnOrder(0);

                    b.Property<string>("AirlineId")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)")
                        .HasColumnName("airline_fk")
                        .HasColumnOrder(1);

                    b.Property<bool?>("CodeshareStatus")
                        .HasColumnType("bit")
                        .HasColumnName("codeshare_status");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.HasKey("RouteId", "AirlineId");

                    b.HasIndex("AirlineId");

                    b.ToTable("route_operator", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Property<string>("SeatId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("seat_id");

                    b.Property<string>("AircraftId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("aircraft_fk");

                    b.Property<int>("CabinClassId")
                        .HasColumnType("int")
                        .HasColumnName("cabin_class_fk");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("IsDeleted");

                    b.Property<bool?>("IsExitRow")
                        .HasColumnType("bit")
                        .HasColumnName("is_exit_row");

                    b.Property<bool?>("IsWindow")
                        .HasColumnType("bit")
                        .HasColumnName("is_window");

                    b.Property<string>("SeatNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("seat_number");

                    b.HasKey("SeatId");

                    b.HasIndex("AircraftId");

                    b.HasIndex("CabinClassId");

                    b.ToTable("seat", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.SuperAdmin", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.HasKey("AppUserId");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("SuperAdmins");
                });

            modelBuilder.Entity("Domain.Entities.Supervisor", b =>
                {
                    b.Property<string>("AppUserId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<string>("AddedById")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId");

                    b.Property<string>("ManagedArea")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AppUserId");

                    b.HasIndex("AddedById");

                    b.HasIndex("EmployeeId")
                        .IsUnique();

                    b.ToTable("Supervisors", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("FlightInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("FrequentFlyerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PassengerId")
                        .HasColumnType("int");

                    b.Property<string>("SeatId")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TicketCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TicketId");

                    b.HasIndex("BookingId");

                    b.HasIndex("FlightInstanceId");

                    b.HasIndex("FrequentFlyerId");

                    b.HasIndex("PassengerId");

                    b.HasIndex("SeatId");

                    b.HasIndex("TicketCode")
                        .IsUnique();

                    b.ToTable("ticket", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("AppUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("AppUserId");

                    b.Property<int?>("FrequentFlyerId")
                        .HasColumnType("int")
                        .HasColumnName("frequent_flyer_fk");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("KrisFlyerTier")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("kris_flyer_tier");

                    b.HasKey("UserId");

                    b.HasIndex("AppUserId")
                        .IsUnique();

                    b.HasIndex("FrequentFlyerId");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.Admin", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("Admin")
                        .HasForeignKey("Domain.Entities.Admin", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne("Admin")
                        .HasForeignKey("Domain.Entities.Admin", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("AppUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Aircraft", b =>
                {
                    b.HasOne("Domain.Entities.AircraftType", "AircraftType")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AircraftTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Airline", "Airline")
                        .WithMany("Aircrafts")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AircraftType");

                    b.Navigation("Airline");
                });

            modelBuilder.Entity("Domain.Entities.AircraftConfig", b =>
                {
                    b.HasOne("Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Configurations")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aircraft");
                });

            modelBuilder.Entity("Domain.Entities.Airline", b =>
                {
                    b.HasOne("Domain.Entities.Airport", "BaseAirport")
                        .WithMany("Airlines")
                        .HasForeignKey("BaseAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BaseAirport");
                });

            modelBuilder.Entity("Domain.Entities.Airport", b =>
                {
                    b.HasOne("Domain.Entities.Country", "Country")
                        .WithMany("Airports")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Domain.Entities.AncillarySale", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("AncillarySales")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AncillaryProduct", "Product")
                        .WithMany("AncillarySales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FlightLegDef", "Segment")
                        .WithMany("AncillarySales")
                        .HasForeignKey("SegmentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("Product");

                    b.Navigation("Segment");
                });

            modelBuilder.Entity("Domain.Entities.Attendant", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("Attendant")
                        .HasForeignKey("Domain.Entities.Attendant", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CrewMember", "CrewMember")
                        .WithOne("Attendant")
                        .HasForeignKey("Domain.Entities.Attendant", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("AppUser");

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("Domain.Entities.BoardingPass", b =>
                {
                    b.HasOne("Domain.Entities.Seat", "Seat")
                        .WithMany("BoardingPasss")
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.BookingPassenger", "BookingPassenger")
                        .WithMany("BoardingPasses")
                        .HasForeignKey("BookingPassengerBookingId", "BookingPassengerPassengerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("BookingPassenger");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.HasOne("Domain.Entities.FareBasisCode", "FareBasisCode")
                        .WithMany("Bookings")
                        .HasForeignKey("FareBasisCodeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FlightInstance", "FlightInstance")
                        .WithMany("Bookings")
                        .HasForeignKey("FlightInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("FareBasisCode");

                    b.Navigation("FlightInstance");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.BookingPassenger", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("BookingPassengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Passenger", "Passenger")
                        .WithMany("BookingPassengers")
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seat", "SeatAssignment")
                        .WithMany("BookingPassengers")
                        .HasForeignKey("SeatAssignmentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Booking");

                    b.Navigation("Passenger");

                    b.Navigation("SeatAssignment");
                });

            modelBuilder.Entity("Domain.Entities.CabinClass", b =>
                {
                    b.HasOne("Domain.Entities.AircraftConfig", "AircraftConfig")
                        .WithMany("CabinClasses")
                        .HasForeignKey("ConfigId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AircraftConfig");
                });

            modelBuilder.Entity("Domain.Entities.Certification", b =>
                {
                    b.HasOne("Domain.Entities.CrewMember", "CrewMember")
                        .WithMany("Certifications")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CrewMember");
                });

            modelBuilder.Entity("Domain.Entities.CrewMember", b =>
                {
                    b.HasOne("Domain.Entities.Airport", "CrewBaseAirport")
                        .WithMany("CrewMembers")
                        .HasForeignKey("CrewBaseAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne("CrewMember")
                        .HasForeignKey("Domain.Entities.CrewMember", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CrewBaseAirport");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("Employee")
                        .HasForeignKey("Domain.Entities.Employee", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Domain.Entities.FlightCrew", b =>
                {
                    b.HasOne("Domain.Entities.CrewMember", "CrewMember")
                        .WithMany("FlightCrews")
                        .HasForeignKey("CrewMemberId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FlightInstance", "FlightInstance")
                        .WithMany("FlightCrews")
                        .HasForeignKey("FlightInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("CrewMember");

                    b.Navigation("FlightInstance");
                });

            modelBuilder.Entity("Domain.Entities.FlightInstance", b =>
                {
                    b.HasOne("Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("FlightInstances")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Domain.Entities.FlightSchedule", "Schedule")
                        .WithMany("FlightInstances")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Domain.Entities.FlightLegDef", b =>
                {
                    b.HasOne("Domain.Entities.Airport", "ArrivalAirport")
                        .WithMany("ArrivalLegs")
                        .HasForeignKey("ArrivalAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Airport", "DepartureAirport")
                        .WithMany("DepartureLegs")
                        .HasForeignKey("DepartureAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FlightSchedule", "Schedule")
                        .WithMany("FlightLegs")
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("ArrivalAirport");

                    b.Navigation("DepartureAirport");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Domain.Entities.FlightSchedule", b =>
                {
                    b.HasOne("Domain.Entities.AircraftType", "AircraftType")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("AircraftTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Airline", "Airline")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Route", "Route")
                        .WithMany("FlightSchedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AircraftType");

                    b.Navigation("Airline");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Domain.Entities.Passenger", b =>
                {
                    b.HasOne("Domain.Entities.User", "User")
                        .WithMany("Passengers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Payment", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("Payments")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("Domain.Entities.Pilot", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.AircraftType", "TypeRating")
                        .WithMany()
                        .HasForeignKey("AircraftTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AircraftType", null)
                        .WithMany("Pilots")
                        .HasForeignKey("AircraftTypeTypeId");

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("Pilot")
                        .HasForeignKey("Domain.Entities.Pilot", "AppUserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CrewMember", "CrewMember")
                        .WithOne("Pilot")
                        .HasForeignKey("Domain.Entities.Pilot", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("AppUser");

                    b.Navigation("CrewMember");

                    b.Navigation("TypeRating");
                });

            modelBuilder.Entity("Domain.Entities.PriceOfferLog", b =>
                {
                    b.HasOne("Domain.Entities.AncillaryProduct", "Ancillary")
                        .WithMany("PriceOfferLogs")
                        .HasForeignKey("AncillaryId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.ContextualPricingAttributes", "ContextAttributes")
                        .WithMany("PriceOfferLogs")
                        .HasForeignKey("ContextAttributesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FareBasisCode", "Fare")
                        .WithMany("PriceOfferLogs")
                        .HasForeignKey("FareId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Ancillary");

                    b.Navigation("ContextAttributes");

                    b.Navigation("Fare");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.HasOne("Domain.Entities.Airport", "DestinationAirport")
                        .WithMany("DestinationRoutes")
                        .HasForeignKey("DestinationAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Airport", "OriginAirport")
                        .WithMany("OriginRoutes")
                        .HasForeignKey("OriginAirportId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("DestinationAirport");

                    b.Navigation("OriginAirport");
                });

            modelBuilder.Entity("Domain.Entities.RouteOperator", b =>
                {
                    b.HasOne("Domain.Entities.Airline", "Airline")
                        .WithMany("RouteOperators")
                        .HasForeignKey("AirlineId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Route", "Route")
                        .WithMany("RouteOperators")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Airline");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.HasOne("Domain.Entities.Aircraft", "Aircraft")
                        .WithMany("Seats")
                        .HasForeignKey("AircraftId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CabinClass", "CabinClass")
                        .WithMany("Seats")
                        .HasForeignKey("CabinClassId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Aircraft");

                    b.Navigation("CabinClass");
                });

            modelBuilder.Entity("Domain.Entities.SuperAdmin", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("SuperAdmin")
                        .HasForeignKey("Domain.Entities.SuperAdmin", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne("SuperAdmin")
                        .HasForeignKey("Domain.Entities.SuperAdmin", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Supervisor", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AddedBy")
                        .WithMany()
                        .HasForeignKey("AddedById");

                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("Supervisor")
                        .HasForeignKey("Domain.Entities.Supervisor", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Employee", "Employee")
                        .WithOne("Supervisor")
                        .HasForeignKey("Domain.Entities.Supervisor", "EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AddedBy");

                    b.Navigation("AppUser");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Booking", "Booking")
                        .WithMany("Tickets")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FlightInstance", "FlightInstance")
                        .WithMany()
                        .HasForeignKey("FlightInstanceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FrequentFlyer", "FrequentFlyer")
                        .WithMany()
                        .HasForeignKey("FrequentFlyerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Passenger", "Passenger")
                        .WithMany()
                        .HasForeignKey("PassengerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Seat", "Seat")
                        .WithMany()
                        .HasForeignKey("SeatId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Booking");

                    b.Navigation("FlightInstance");

                    b.Navigation("FrequentFlyer");

                    b.Navigation("Passenger");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", "AppUser")
                        .WithOne("User")
                        .HasForeignKey("Domain.Entities.User", "AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.FrequentFlyer", "FrequentFlyer")
                        .WithMany("User")
                        .HasForeignKey("FrequentFlyerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AppUser");

                    b.Navigation("FrequentFlyer");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Aircraft", b =>
                {
                    b.Navigation("Configurations");

                    b.Navigation("FlightInstances");

                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.AircraftConfig", b =>
                {
                    b.Navigation("CabinClasses");
                });

            modelBuilder.Entity("Domain.Entities.AircraftType", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("FlightSchedules");

                    b.Navigation("Pilots");
                });

            modelBuilder.Entity("Domain.Entities.Airline", b =>
                {
                    b.Navigation("Aircrafts");

                    b.Navigation("FlightSchedules");

                    b.Navigation("RouteOperators");
                });

            modelBuilder.Entity("Domain.Entities.Airport", b =>
                {
                    b.Navigation("Airlines");

                    b.Navigation("ArrivalLegs");

                    b.Navigation("CrewMembers");

                    b.Navigation("DepartureLegs");

                    b.Navigation("DestinationRoutes");

                    b.Navigation("OriginRoutes");
                });

            modelBuilder.Entity("Domain.Entities.AncillaryProduct", b =>
                {
                    b.Navigation("AncillarySales");

                    b.Navigation("PriceOfferLogs");
                });

            modelBuilder.Entity("Domain.Entities.AppUser", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("Attendant");

                    b.Navigation("Employee");

                    b.Navigation("Pilot");

                    b.Navigation("SuperAdmin");

                    b.Navigation("Supervisor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Booking", b =>
                {
                    b.Navigation("AncillarySales");

                    b.Navigation("BookingPassengers");

                    b.Navigation("Payments");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.BookingPassenger", b =>
                {
                    b.Navigation("BoardingPasses");
                });

            modelBuilder.Entity("Domain.Entities.CabinClass", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Domain.Entities.ContextualPricingAttributes", b =>
                {
                    b.Navigation("PriceOfferLogs");
                });

            modelBuilder.Entity("Domain.Entities.Country", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("Domain.Entities.CrewMember", b =>
                {
                    b.Navigation("Attendant");

                    b.Navigation("Certifications");

                    b.Navigation("FlightCrews");

                    b.Navigation("Pilot");
                });

            modelBuilder.Entity("Domain.Entities.Employee", b =>
                {
                    b.Navigation("Admin");

                    b.Navigation("CrewMember");

                    b.Navigation("SuperAdmin");

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("Domain.Entities.FareBasisCode", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("PriceOfferLogs");
                });

            modelBuilder.Entity("Domain.Entities.FlightInstance", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("FlightCrews");
                });

            modelBuilder.Entity("Domain.Entities.FlightLegDef", b =>
                {
                    b.Navigation("AncillarySales");
                });

            modelBuilder.Entity("Domain.Entities.FlightSchedule", b =>
                {
                    b.Navigation("FlightInstances");

                    b.Navigation("FlightLegs");
                });

            modelBuilder.Entity("Domain.Entities.FrequentFlyer", b =>
                {
                    b.Navigation("User");
                });

            modelBuilder.Entity("Domain.Entities.Passenger", b =>
                {
                    b.Navigation("BookingPassengers");
                });

            modelBuilder.Entity("Domain.Entities.Route", b =>
                {
                    b.Navigation("FlightSchedules");

                    b.Navigation("RouteOperators");
                });

            modelBuilder.Entity("Domain.Entities.Seat", b =>
                {
                    b.Navigation("BoardingPasss");

                    b.Navigation("BookingPassengers");
                });

            modelBuilder.Entity("Domain.Entities.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
