using Application.DTOs.Seat;
using Application.DTOs.Aircraft;  
using AutoMapper;
using Domain.Entities;
using System.Linq;  

namespace Application.Maps
{
    // This is now the central profile for ALL Seat-related mappings
    public class SeatMappingProfile : Profile
    {
        public SeatMappingProfile()
        {
            // Map Seat (Entity) to SeatDto (Customer-facing)
            CreateMap<Seat, SeatDto>()
                .ForMember(dest => dest.CabinClassName, opt => opt.MapFrom(src => src.CabinClass.Name))
                .ForMember(dest => dest.AircraftTailNumber, opt => opt.MapFrom(src => src.AircraftId))
                .ForMember(dest => dest.IsAisle, opt => opt.MapFrom(src => CalculateIsAisle(src.SeatNumber)))
                .ForMember(dest => dest.IsAvailable, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.SeatPrice, opt => opt.Ignore()); // Set by service

            // Map BookingPassenger (Entity) to SeatAssignmentDto
            CreateMap<BookingPassenger, SeatAssignmentDto>()
                .ForMember(dest => dest.BookingId, opt => opt.MapFrom(src => src.BookingId))
                .ForMember(dest => dest.PassengerId, opt => opt.MapFrom(src => src.PassengerId))
                .ForMember(dest => dest.PassengerName, opt => opt.MapFrom(src => $"{src.Passenger.FirstName} {src.Passenger.LastName}"))
                .ForMember(dest => dest.SeatId, opt => opt.MapFrom(src => src.SeatAssignmentId))
                .ForMember(dest => dest.SeatNumber, opt => opt.MapFrom(src => src.SeatAssignment.SeatNumber))
                .ForMember(dest => dest.CabinClassName, opt => opt.MapFrom(src => src.SeatAssignment.CabinClass.Name));

           

            // Map Create DTO (Admin) to Seat Entity
            CreateMap<CreateSeatDto, Seat>()
                .ForMember(dest => dest.SeatId, opt => opt.Ignore()) // Generated by service
                .ForMember(dest => dest.AircraftId, opt => opt.Ignore()) // Set by service
                .ForMember(dest => dest.SeatNumber, opt => opt.MapFrom(src => src.SeatNumber.ToUpper()));

            // Map Update DTO (Admin) to Seat Entity
            CreateMap<UpdateSeatDto, Seat>()
                .ForMember(dest => dest.SeatId, opt => opt.Ignore())
                .ForMember(dest => dest.AircraftId, opt => opt.Ignore())
                .ForMember(dest => dest.SeatNumber, opt => opt.Ignore()); // Usually SeatNumber is not updatable
        }

        // Helper function
        private bool CalculateIsAisle(string seatNumber)
        {
            if (string.IsNullOrEmpty(seatNumber)) return false;
            char lastChar = seatNumber.ToUpperInvariant().Last();
            return lastChar == 'C' || lastChar == 'D' || lastChar == 'G' || lastChar == 'H';
        }
    }
}