using Domain.Entities;
using Infrastructure.Data.DataSeeding.DataSeedingDTOs;
using Infrastructure.Data.DataSeeding.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Linq;
using System.Threading.Tasks;

namespace Infrastructure.Data.DataSeeding.Seeders
{
    /// <summary>
    /// Professional Seeder for the BoardingPass entity, handling data insertion from a JSON file.
    /// Responsibility: Read, validate, and insert BoardingPass records, and reset the IDENTITY counter (pass_id).
    /// </summary>
    public class BoardingPassSeeder
    {
        private readonly ApplicationDbContext _context; 
        private readonly ILogger<BoardingPassSeeder> _logger;
        private const string JsonFileName = "BoardingPass.json";
        private const string TableName = "BoardingPass"; // Entity name, often matches the table name for EF Core (or check DB: 'boarding_pass')
        private const string DbTableName = "boarding_pass"; // Actual table name for DBCC CHECKIDENT

        public BoardingPassSeeder(ApplicationDbContext context, ILogger<BoardingPassSeeder> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// Executes the BoardingPass data seeding process using JSON deserialization and identity reset.
        /// </summary>
        public async Task SeedAsync()
        {
            _logger.LogInformation("Starting BoardingPass Seeding process...");

            try
            {
                // 1. Check if data already exists to prevent duplicate seeding
                if (await _context.Set<BoardingPass>().AnyAsync())
                {
                    _logger.LogInformation("{TableName} table already contains data. Skipping seeding.", TableName);
                    return;
                }

                await JsonDataSeederHelper.ResetIdentityCounterAsync(_context, DbTableName);

                // 2. Read and deserialize data from JSON file using the professional helper
                var dtos = await JsonDataSeederHelper.ReadAndDeserializeJsonAsync<BoardingPassSeedDto>(
                    JsonFileName, _logger);

                if (dtos == null || !dtos.Any())
                {
                    _logger.LogWarning("No data found in '{JsonFileName}'. Skipping seeding.", JsonFileName);
                    return;
                }

                // 3. Map DTOs to Entity objects
                var entities = dtos.Select(dto => new BoardingPass
                {
                    // PassId is auto-generated by the database (IDENTITY)  
                    BookingPassengerBookingId = dto.BookingPassengerBookingId,
                    BookingPassengerPassengerId = dto.BookingPassengerPassengerId, 
                    SeatId = dto.SeatId,  
                    BoardingTime = dto.BoardingTime,
                    PrecheckStatus = dto.PrecheckStatus,  
                    IsDeleted = dto.IsDeleted
                }).ToList();

                // 4. Add entities to the context and save changes
                await _context.Set<BoardingPass>().AddRangeAsync(entities);
                await _context.SaveChangesAsync();
                 

                _logger.LogInformation("{TableName} Seeding completed: Successfully seeded {Count} records.", TableName, entities.Count);
            }
            catch (Exception ex)
            {
                _logger.LogCritical(ex, "FATAL ERROR during {TableName} seeding process.", TableName);
                throw; // Re-throw the exception to ensure failed seeding is noticed
            }
        }
    }
}