using Domain.Entities;
using Infrastructure.Data.DataSeeding.DataSeedingDTOs;
using Infrastructure.Data.DataSeeding.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System;
  
namespace Infrastructure.Data.DataSeeding.Seeders
{
    /// <summary>
    /// Professional Seeder for the Booking entity.
    /// Responsibility: Reads booking data from a JSON file and seeds them into the database.
    /// It ensures ID consistency and respects foreign key constraints (User, FlightInstance, FareBasisCode).
    /// </summary>
    public class BookingSeeder  
    {
        private readonly ApplicationDbContext _context;
        private readonly ILogger<BookingSeeder> _logger;
        private const string JsonFileName = "Booking.json";
        private const string TableName = "booking"; // SQL table name for IDENTITY reset (from Creation SingaporeDb.sql)

        public BookingSeeder(
            ApplicationDbContext context,
            ILogger<BookingSeeder> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// Executes the Booking data seeding process.
        /// </summary>
        public async Task SeedAsync()
        {
            _logger.LogInformation("Starting Booking data seeding process from {JsonFileName}...", JsonFileName);

            try
            {
                // 1. Check if the table already contains data to prevent duplication on multiple runs.
                if (await _context.Set<Booking>().AnyAsync())
                {
                    _logger.LogInformation("Booking table already contains data. Skipping seeding.");
                    return;
                }

                // Reset the Identity Counter using the specialized helper method.
                // This is crucial to ensure the database IDENTITY sequence is in sync after explicit seeding.
                await JsonDataSeederHelper.ResetIdentityCounterAsync(_context, TableName );

                // 2. Read and deserialize the JSON data using the helper method.
                var bookingsDto = await JsonDataSeederHelper.ReadAndDeserializeJsonAsync<BookingSeedDto>(JsonFileName, _logger);

                if (bookingsDto == null || !bookingsDto.Any())
                {
                    _logger.LogError("Deserialization failed or {JsonFileName} is empty.", JsonFileName);
                    return;
                }

                // 3. Convert DTOs to Entity objects.
                var bookings = new List<Booking>();
                foreach (var dto in bookingsDto)
                {
                    bookings.Add(new Booking
                    {
                        // BookingId is auto-generated by DB (IDENTITY)
                        UserId = dto.UserId,
                        FlightInstanceId = dto.FlightInstanceId,
                        BookingRef = dto.BookingRef,
                        BookingTime = dto.BookingTime,
                        PriceTotal = dto.PriceTotal,
                        PaymentStatus = dto.PaymentStatus,
                        FareBasisCodeId = dto.FareBasisCodeId,
                        PointsAwarded = dto.PointsAwarded,
                        IsDeleted = dto.IsDeleted
                    });
                }

                // 4. Add the entities to the DbContext.
                await _context.Set<Booking>().AddRangeAsync(bookings);

                // 5. Save changes to the database.
                await _context.SaveChangesAsync();

 
                _logger.LogInformation("Booking Seeding completed: Successfully seeded {Count} records.", bookings.Count);
            }
            catch (Exception ex)
            {
                _logger.LogCritical(ex, "FATAL ERROR during Booking seeding process from {JsonFileName}.", JsonFileName);
                throw;
            }
        }
    }
}