using Domain.Entities;
using Infrastructure.Data.DataSeeding.DataSeedingDTOs;
using Infrastructure.Data.DataSeeding.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System.Linq;
using System.Threading.Tasks;
using System.Collections.Generic;

namespace Infrastructure.Data.DataSeeding.Seeders
{
    /// <summary>
    /// Professional Seeder for the PriceOfferLog entity.
    /// This seeder logs various price quotes for both flight fares (FareBasisCode) 
    /// and ancillary products, considering contextual pricing attributes.
    /// </summary>
    public class PriceOfferLogSeeder
    {
        private readonly ApplicationDbContext _context;  
        private readonly ILogger<PriceOfferLogSeeder> _logger;
        private const string JsonFileName = "PriceOfferLog.json";
        private const string TableName = "price_offer_log"; // Table name in the database

        public PriceOfferLogSeeder(
            ApplicationDbContext context,
            ILogger<PriceOfferLogSeeder> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// Executes the seeding logic for PriceOfferLog.
        /// Reads data from JSON, maps it to entities, and inserts them into the database.
        /// </summary>
        public async Task SeedAsync()
        {
            // 1. Check if the table is already seeded.
            if (await _context.Set<PriceOfferLog>().AnyAsync())
            {
                _logger.LogInformation("PriceOfferLog table already contains data. Skipping seeding.");
                return;
            }

            try
            {
                _logger.LogInformation("Starting PriceOfferLog data seeding process...");

                // 1. Reset the IDENTITY counter using the professional helper method
                await JsonDataSeederHelper.ResetIdentityCounterAsync(_context, TableName);


                // 2. Read and Deserialize JSON data using the professional helper method
                List<PriceOfferLogSeedDto> dtos = await JsonDataSeederHelper.ReadAndDeserializeJsonAsync<PriceOfferLogSeedDto>(
                    JsonFileName,
                    _logger);

                if (dtos == null || !dtos.Any())
                {
                    _logger.LogWarning("No data found in '{JsonFileName}'. PriceOfferLog seeding aborted.", JsonFileName);
                    return;
                }

                // 3. Map DTOs to Entities
                var entities = dtos.Select(dto => new PriceOfferLog
                {
                    // OfferId is IDENTITY and will be generated by the database
                    ProductId = dto.ProductId,
                    OfferPriceQuote = dto.OfferPriceQuote,
                    Timestamp = dto.Timestamp,
                    ContextAttributesId = dto.ContextAttributesId, // FK to ContextualPricingAttributes
                    FareId = dto.FareId, // FK to FareBasisCode (nullable)
                    AncillaryId = dto.AncillaryId, // FK to AncillaryProduct (nullable)
                    IsDeleted = dto.IsDeleted
                }).ToList();

                // 4. Insert entities and save changes
                _context.Set<PriceOfferLog>().AddRange(entities);
                await _context.SaveChangesAsync();
                 

                _logger.LogInformation("PriceOfferLog Seeding completed successfully. Seeded {Count} records.", entities.Count);
            }
            catch (System.Exception ex)
            {
                _logger.LogCritical(ex, "FATAL ERROR during PriceOfferLog seeding process.");
                throw; // Re-throw to propagate the failure
            }
        }
    }
}