using Domain.Entities;
using Infrastructure.Data.DataSeeding.DataSeedingDTOs;
using Infrastructure.Data.DataSeeding.Helpers;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Infrastructure.Data.DataSeeding.Seeders
{
    /// <summary>
    /// Professional Seeder for the Route entity.
    /// Responsibility: Reads Route data from JSON, maps it to the entity, and seeds the database.
    /// Dependency: Must run after the Airport table has been successfully seeded.
    /// </summary>
    public class RouteSeeder
    {
        private readonly ApplicationDbContext _context;  
        private readonly ILogger<RouteSeeder> _logger;
        private const string JsonFileName = "Route.json";
        private const string TableName = "route"; // Table name for IDENTITY reset

        public RouteSeeder(ApplicationDbContext context, ILogger<RouteSeeder> logger)
        {
            _context = context;
            _logger = logger;
        }

        /// <summary>
        /// Executes the data seeding process for Route entities.
        /// </summary>
        public async Task SeedAsync()
        {
            try
            {
                // Check if any records already exist to prevent duplicate seeding
                if (await _context.Set<Route>().AnyAsync())
                {
                    _logger.LogInformation("Route table already contains data. Skipping seeding.");
                    return;
                }

                await JsonDataSeederHelper.ResetIdentityCounterAsync(_context, TableName);

                _logger.LogInformation("Starting Route Data Seeding process...");

                // 1. Read and deserialize data from JSON file using the dedicated helper method
                var routeDtos = await JsonDataSeederHelper.ReadAndDeserializeJsonAsync<RouteSeedDto>(JsonFileName, _logger);
                var routesToSeed = new List<Route>();

                // 2. Map DTOs to Entity objects
                foreach (var dto in routeDtos)
                {
                    routesToSeed.Add(new Route
                    {
                        OriginAirportId = dto.OriginAirportId,
                        DestinationAirportId = dto.DestinationAirportId,
                        DistanceKm = dto.DistanceKm,
                        IsDeleted = dto.IsDeleted
                        // RouteId (PK) is an IDENTITY column and will be generated by the database.
                    });
                }

                // 3. Add entities to the context
                await _context.Set<Route>().AddRangeAsync(routesToSeed);

                // 4. Save changes to the database
                await _context.SaveChangesAsync();

                // 5. Reset IDENTITY counter for the 'route' table to ensure sequence continuity
                await JsonDataSeederHelper.ResetIdentityCounterAsync(_context, TableName);

                _logger.LogInformation("Route Seeding completed successfully: Seeded {Count} routes.", routesToSeed.Count);
            }
            catch (Exception ex)
            {
                _logger.LogCritical(ex, "FATAL ERROR during Route seeding process.");
                throw;
            }
        }
    }
}